reg add "HKCU\Software\Wine\DllOverrides" /v "atl100" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "msvcp100" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "msvcr100" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "vcomp100" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "atl110" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "msvcp110" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "msvcr110" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "vcomp110" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "atl120" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "msvcp120" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "msvcr120" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "vcomp120" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "api-ms-win-crt-conio-l1-1-0" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "api-ms-win-crt-heap-l1-1-0" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "api-ms-win-crt-locale-l1-1-0" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "api-ms-win-crt-math-l1-1-0" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "api-ms-win-crt-runtime-l1-1-0" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "api-ms-win-crt-stdio-l1-1-0" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "api-ms-win-crt-time-l1-1-0" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "atl140" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "concrt140" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "msvcp140" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "msvcr140" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "ucrtbase" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "vcomp140" /t REG_SZ /d "native,builtin" /f
reg add "HKCU\Software\Wine\DllOverrides" /v "vcruntime140" /t REG_SZ /d "native,builtin" /f